import 'dart:collection';
import 'dart:io' as Io;
import 'dart:async';
import 'dart:io';
import 'dart:math';
import 'package:app1/Favorit.dart';
import 'package:app1/affich.dart';
import 'package:app1/main.dart';
import 'package:app1/splash.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// class Categorys {
//   String name;
//   String url;
//   bool isfavorit;
//   bool Onepiece;
//   bool Naruto;
//   bool Spyxf;
//   bool Attack;
//   Categorys(
//       {required this.name,
//       required this.url,
//       required this.isfavorit,
//       required this.Onepiece,
//       required this.Attack,
//       required this.Naruto,
//       required this.Spyxf});
// }

// List<Categorys> Categorydata = [
//   Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//    Categorys(
//     name: 'One piece',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//   Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//     Categorys(
//     name: 'Naruto',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
//   Categorys(
//     name: 'Attack',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: true,
//     Naruto: false,
//     Spyxf: false,
//   ),
//   Categorys(
//     name: 'Spy x family',
//     url: "",
//     isfavorit: false,
//     Onepiece: false,
//     Attack: false,
//     Naruto: false,
//     Spyxf: false,
//   ),
// ];
final List<String> onepiece = [
  'lib/imges/1.jpg',
  'lib/imges/2.jpg',
  'lib/imges/3.jpg',
  'lib/imges/4.jpg',
  'lib/imges/5.jpg',
  'lib/imges/6.jpg',
  'lib/imges/7.jpg',
  'lib/imges/8.jpg',
  'lib/imges/9.jpg',
  'lib/imges/10.jpg',
];
final List<String> spyx = [
  'lib/imges/21.jpg',
  'lib/imges/22.jpg',
  'lib/imges/23.jpg',
  'lib/imges/24.jpg',
  'lib/imges/25.jpg',
  'lib/imges/26.jpg',
  'lib/imges/27.jpg',
  'lib/imges/28.jpg',
  'lib/imges/29.jpg',
  'lib/imges/30.jpg',
  'lib/imges/31.jpg',
];
final List<String> attack = [
   'lib/imges/32.jpg',
  'lib/imges/33.jpg',
  'lib/imges/34.jpg',
  'lib/imges/35.jpg',
  'lib/imges/36.jpg',
  'lib/imges/37.jpg',
  'lib/imges/38.jpg',
  'lib/imges/39.jpg',
  'lib/imges/40.jpg',
  'lib/imges/41.jpg',
  'lib/imges/42.jpg',
  'lib/imges/43.jpg',
  'lib/imges/44.jpg',
];
final List<String> naruto = [
  'lib/imges/11.jpg',
  'lib/imges/12.jpg',
  'lib/imges/13.jpg',
  'lib/imges/14.jpg',
  'lib/imges/15.jpg',
  'lib/imges/16.jpg',
  'lib/imges/17.jpg',
  'lib/imges/18.jpg',
  'lib/imges/19.jpg',
  'lib/imges/20.jpg',
];
final List<String> listitem = [
  'lib/imges/1.jpg',
  'lib/imges/2.jpg',
  'lib/imges/3.jpg',
  'lib/imges/4.jpg',
  'lib/imges/5.jpg',
  'lib/imges/6.jpg',
  'lib/imges/7.jpg',
  'lib/imges/8.jpg',
  'lib/imges/9.jpg',
  'lib/imges/10.jpg',
  'lib/imges/11.jpg',
  'lib/imges/12.jpg',
  'lib/imges/13.jpg',
  'lib/imges/14.jpg',
  'lib/imges/15.jpg',
  'lib/imges/16.jpg',
  'lib/imges/17.jpg',
  'lib/imges/18.jpg',
  'lib/imges/19.jpg',
  'lib/imges/20.jpg',
  'lib/imges/21.jpg',
  'lib/imges/22.jpg',
  'lib/imges/23.jpg',
  'lib/imges/24.jpg',
  'lib/imges/25.jpg',
  'lib/imges/26.jpg',
  'lib/imges/27.jpg',
  'lib/imges/28.jpg',
  'lib/imges/29.jpg',
  'lib/imges/30.jpg',
  'lib/imges/31.jpg',
  'lib/imges/32.jpg',
  'lib/imges/33.jpg',
  'lib/imges/34.jpg',
  'lib/imges/35.jpg',
  'lib/imges/36.jpg',
  'lib/imges/37.jpg',
  'lib/imges/38.jpg',
  'lib/imges/39.jpg',
  'lib/imges/40.jpg',
  'lib/imges/41.jpg',
  'lib/imges/42.jpg',
  'lib/imges/43.jpg',
  'lib/imges/44.jpg',
];
